Feat : 거래 요청 목록과 요청 받은 거래 목록 조회 기능 구현
Team-Piglin/swapswap pull request #102
Opened 2024-01-18 12:29 UTC by ckdnqls

## 📝 개요
- 거래요청 목록 조회, 요청 받은 거래 목록 조회 구현
<br>

## 👨‍💻 작업 내용
- 메인 홈페이지에서 스왑목록을 누르면 거래요청 목록 조회 페이지로 이동 가능 하도록 하였습니다.
- 거래요청 목록 조회 페이지에서 요청 받은 거래 목록 조회 페이지로 이동 가능 하도록 하였습니다.
<br>

## 🙇🏻‍♂️ 리뷰어에게
- 코드에서 오류부분이나 컨벤션에 맞지 않는 코드가 있으면(개선 사항) 코멘트 달아주시면 감사하겠습니다.
<br>

2024-01-18 12:47 UTC, wonowonow requested changes
제가 코멘트 남긴 부분 수정하시면 될 거 같습니다~

2024-01-18 12:47 UTC, wonowonow commented on src/main/java/piglin/swapswap/domain/deal/controller/DealController.java
> +        return "deals/" + dealId;
이렇게하면 템플릿에 있는 걸 찾을 거에요 그래서 redirect로 수정하는 게 나을 거 같습니다

2024-01-18 12:47 UTC, wonowonow commented on src/main/java/piglin/swapswap/domain/deal/repository/DealQueryRepositoryImpl.java
> +    public List<DealGetResponseDto> findALlMyDealResponse(Member member) {
여기 오타있어요!!!!!!

2024-01-18 12:47 UTC, wonowonow commented on src/main/resources/templates/common/fragments/nav.html
> +            <a href="deals/request/list" class="login-link deal-request-list-link">스왑목록</a>
이러면 상대경로로 빠져서 만약 localhost/main 에서 이 버튼을 눌렀을 때 localhost/main/deals/request/list 로 빠져요~ 그래서 /deals 로 하는 게 좋을 거 같아요~

2024-01-18 12:49 UTC, sungpal commented on src/main/java/piglin/swapswap/domain/deal/repository/DealQueryRepositoryImpl.java
> +    public List<DealGetResponseDto> findALlMyDealResponse(Member member) {
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-01-19 00:07 UTC, mistarson requested changes

2024-01-19 00:07 UTC, mistarson commented on src/main/java/piglin/swapswap/domain/deal/repository/DealRepository.java
>  @Repository
해당 어노테이션도 제거해도 될것 같습니다.

2024-01-19 04:01 UTC, wonowonow reviewed
수정해주셉쇼~~~~~~~

2024-01-19 04:01 UTC, wonowonow commented on src/main/java/piglin/swapswap/domain/deal/controller/DealController.java
> +        return "redirect:deals/" + dealId;
여기 어제 말씀드린 것처럼 상대 경로로 리다이렉트 될 거 같습니다.
혹시 모르니 절대 경로로 하시는 게 좋습니다.

2024-01-19 04:15 UTC, merged