Refactor: 엔티티간 연관관계를 가능한 가지지 않는 방향으로 리팩토링
Team-Piglin/swapswap pull request #208
Opened 2024-01-25 18:35 UTC by MoonKiHyun

## 📝 개요
- 엔티티간에 연관관계를 가지지 않는 방향으로 재설계 하였습니다.
- ChatRoomMember 클래스는 더 이상 사용하지 않습니다.
<br>

## 👨‍💻 작업 내용
- ChatRoom과 Message가 Member와 갖고 있던 연관관계를 제거하고 String 값이나 Long 값으로 id, nickname 값을 가지고 있도록 하였습니다.
- 채팅방 목록을 가져오는 메소드를 QueryDSL을 사용하여 작성하였지만 제대로 작동하지 않아 기존과 다르게 작성하였습니다.
- ChatRoomMember 클래스는 더 이상 사용하지 않습니다만 아직 삭제하지는 않았습니다.
- UserDetailsImpl에 회원의 id를 반환 받는 메소드를 작성하였습니다.

- 추가
- ChatRoom 엔티티에 isLeaveFirstMember, isLeaveSecondMember 필드를 추가해서 채팅방에서 회원이 나갈 시 null 값으로 만들지 않고 해당 필드를 true로 바꾸어 채팅방을 나간 후에도 해당 채팅방에 참여한 회원을 알 수 있도록 하였습니다.
- RequestParam으로 값을 받고 있던 부분을 제거하였습니다.
<img width="629" alt="image" src="https://github.com/Team-Piglin/swapswap/assets/120175285/9f8d60f8-8d99-4edc-acf9-b7d7db72795d">

<br>

## 🙇🏻‍♂️ 리뷰어에게
- ChatRoomServierImpl.class에 getChatRoomResponseDtoList 메소드가 채팅방 목록을 가져오는 메소드 입니다.
- 좋은 코드인 것 같지는 않아서 더 좋은 방법이 있다면 알려주시면 감사하겠습니다. 
<br>

2024-01-25 18:54 UTC, sungpal commented
대격변이 일어났네요

2024-01-25 19:42 UTC, wonowonow requested changes
채팅관련으로 잘 몰라서 코멘트를 잘 못남겨 드렸었는데, 이번에 바꾸신 구조는 조금 구조가 이해하기 힘들다는 생각이 듭니다. 그리고 과연 이렇게 짜는 게 좋은 방법일까? 쪽으로 생각해봤을때도 아니라는 생각이 들어서 제가 방금 말씀드린 부분 내일 같이 로직 수정해보도록 하는 걸로 해봅시다 !!

2024-01-25 19:42 UTC, wonowonow commented on src/main/java/piglin/swapswap/domain/chatroom/entity/ChatRoom.java
> +    private Long secondMemberId;
저는 채팅방 나가기를 했을 때 삭제할 목적으로 Nullable True를 주신 게 이해가 안됩니다.
한 사람이 나가면 상대 입장에서는 채팅방 상대가 안 불러와져서 많이 당황할 거 같은데 first second 나갔다는 boolean 을 추가하는 것이 좋아보입니다. db 관리하는 입장에서도 그게 더 보기 좋을 거 같아요

2024-01-25 19:42 UTC, wonowonow commented on src/main/java/piglin/swapswap/domain/chatroom/controller/ChatRoomController.java
> +            @RequestParam(name = "nickname", required = false) String nickname,
여기에서 nickname을 파람으로 받아올 필요가 있을까도 의구심이 듭니다. 이미 데이터적으로 잘 표현된 구조라면 param을 안쓰고 dto로 받아서 로그인한 멤버인지 구분을 짓고 표현을 해줄 수 있을 거 같습니다.

2024-01-26 07:27 UTC, MoonKiHyun commented on src/main/java/piglin/swapswap/domain/chatroom/entity/ChatRoom.java
> +    private Long secondMemberId;
네 해당 필드를 추가하는 방향으로 잡아보겠습니다.

2024-01-26 17:22 UTC, wonowonow commented on src/main/java/piglin/swapswap/domain/chatroom/repository/ChatRoomQueryRepositoryImpl.java
>                          .where(conditions)
.where(conditions.and(chatRoom.isDeleted.eq(false))) 로 하는게 좋을 거 같아요

2024-01-26 17:22 UTC, wonowonow commented on src/main/java/piglin/swapswap/domain/chatroom/service/ChatRoomServiceImpl.java
>          return chatRoomList.stream()
맵퍼 써주세요

2024-01-26 19:46 UTC, merged